### ISSUE TITLE
Extend user-defined history outputs beyond parallel summed quantities 

### ISSUE THREAD

**Issue by felker** [PrincetonUniversity/athena#237]
## Description
The need for such an extension became apparent to me when I was running tests that measured the decay of viscous, resistive MHD linear waves. Currently, the regression test that performs a variant of this test relies on writing out a full 3D dataset at each output timeslice in order to compute a simple primitive variable maximum in Python:
https://github.com/PrincetonUniversity/athena/blob/db3f009c91eb4cbc61672ce14a57f406437f4c04/tst/regression/scripts/tests/diffusion/linear_wave3d.py#L56-L57

Therefore, I added a very simple  [User-Defined History Output](https://github.com/PrincetonUniversity/athena/wiki/Outputs#user-defined-history-output) to `pgen/linear_wave.cpp`:
```c++

...

Real max_v2(MeshBlock *pmb, int iout);
 } // namespace


...

// @@ -84,6 +87,9 @@ void Mesh::InitUserMeshData(ParameterInput *pin) {
   ang_2_vert = pin->GetOrAddBoolean("problem", "ang_2_vert", false);
   ang_3_vert = pin->GetOrAddBoolean("problem", "ang_3_vert", false);

  AllocateUserHistoryOutput(1);
  EnrollUserHistoryOutput(0, max_v2, "max(v2)");

...

namespace {
Real max_v2(MeshBlock *pmb, int iout) {
  Real max_v2=0.0;
  int is=pmb->is, ie=pmb->ie, js=pmb->js, je=pmb->je, ks=pmb->ks, ke=pmb->ke;
  AthenaArray<Real> &w = pmb->phydro->w;
  for (int k=ks; k<=ke; k++) {
    for (int j=js; j<=je; j++) {
      for (int i=is; i<=ie; i++) {
        max_v2 = std::max(std::abs(w(IVY,k,j,i)), max_v2);
      }
    }
  }
  return max_v2;
}
} // namespace
```

However, I realized that the Wiki page notes (not very prominently):
> The history output automatically calculates a global sum using this function. 

So clearly my user-defined `.hst` output would be incompatible with multiple MeshBlock (including parallel) simulations. This restriction is written in the source code in two places:
https://github.com/PrincetonUniversity/athena/blob/db3f009c91eb4cbc61672ce14a57f406437f4c04/src/outputs/history.cpp#L94-L99

https://github.com/PrincetonUniversity/athena/blob/db3f009c91eb4cbc61672ce14a57f406437f4c04/src/outputs/history.cpp#L101-L110

We could relax this constraint by:
1. rename `data_sum` to `data`, and generalize the `+=` operator to other operations like `= std::max(`, etc.
2. allowing the user to specify other MPI [Predefined Reduce Operations](https://www.open-mpi.org/doc/v2.0/man3/MPI_Reduce.3.php) like `MPI_MAX`. 

But I am not sure of the best way to add such a switch to:
```c++
void Mesh::EnrollUserHistoryOutput(int i, HistoryOutputFunc my_func, const char *name);
```
Is there any other demand for such a feature?

**To-do:**
- [x] Add `max_v2()` function to `linear_wave.cpp`
- [ ] Update Wiki page [User-Defined History Output](https://github.com/PrincetonUniversity/athena/wiki/Outputs#user-defined-history-output) to more explicitly identify restrictions of this feature.
- [x] Update `diffusion/` regression test scripts to use the simpler `.hst` output instead of full `.vtk` outputs. 
- [ ] Similarly, should we extend `x[1,2,3]_slice, x[1,2,3]_sum` to `_max`, `_min`, etc. options in the `<output[n]>` block in the input file?
